name: Build

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings -W rust-2021-compatibility"
  RUSTUP_MAX_RETRIES: 10

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
    tags:
      - "nockapp-*"
      - "choo-*"

jobs:
  build:
    name: "Build Nockapp"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: zorp-corp/rust-cache@v2
      with:
        workspaces: ". -> target"
    - name: Build all
      run: cargo build --release
    - name: Compile choo kernel with bootstrap choo
      run: target/release/choo choo/hoon/lib/kernel.hoon choo/hoon
    - name: Move choo jam back into assets
      run: mv out.jam choo/bootstrap/choo.jam
    - name: Rebuild choo with built jamfile
      run: cargo build --release --bin choo
    - name: Release Choo Artifact
      if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'choo') }}
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/release/choo

